### ISSUE TITLE
npm run test 的时候报错

### ISSUE THREAD

**Issue by faymi** [node-weixin/node-weixin-pay#4]
请问一下，在npm run test 的时候报了以下的错误（Invalid Merchant Data: {"key":"key","reason":"Key key is NULL"}），小白不知道怎么解决这个问题呀
```
f:\faymi\git_project\node-weixin-pay\gulpfile.js:40
      throw err;
Error: Invalid Merchant Data: {"key":"key","reason":"Key key is NULL"}
    at Error (native)
    at Object.init (f:\faymi\git_project\node-weixin-pay\node_modules\node-weixin-config\lib\merchant.js:7:13)
    at Object.<anonymous> (f:\faymi\git_project\node-weixin-pay\test\api.js:22:27)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Object.Module._extensions.(anonymous function) [as .js] (f:\faymi\git_project\node-weixin-pay\node_modules\istanbul\lib\hook.js:109:37)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
```

**Comment by calidion** [comment]
这里不负责回答问题。问题请到QQ群或者论坛上提。
